load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "math_helper_lib",
    srcs = ["MathHelper.kt"],
    visibility = ["//visibility:public"],
)

kt_jvm_library(
    name = "string_helper_lib",
    srcs = ["StringHelper.kt"],
    visibility = ["//visibility:public"],
)
